spring:
  config:
    import: optional:file:./secrets.properties
  application:
    name: deen-quest-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/deen-quest-db
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true